Added a flag --ptr_conservative. When enabled, the alias analysis treats undefined functions conservatively.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1892,9 +1892,9 @@ echo $ECHO_N "checking for Perl... $ECHO_C" >&6
       You can get perl at http://www.cpan.org/src/index.html .
     " >&5
 echo "$as_me: error:
-      perl not found.
+      perl not found.#
       You need perl version 5.6.1 or later for CCured.
-      You can get perl at http://www.cpan.org/src/index.html .
+     You can get perl at http://www.cpan.org/src/index.html .
     " >&2;}
    { (exit 1); exit 1; }; }
   fi
@@ -1905,17 +1905,17 @@ echo "$as_me: error:
   # of autoconf's quoting characters, so I use the "quadrigraph" ]
   # to stand for right-bracket.  what a mess.
   perlver=`perl -e 'print($]);'`
-  if perl -e "exit( $perlver >= 5.006001 );"; then
-    { { echo "$as_me:1909: error:
-      Found perl version $perlver, but at least 5.6.1 is required.
-      You can get a newer perl at http://www.cpan.org/src/index.html .
-    " >&5
-echo "$as_me: error:
-      Found perl version $perlver, but at least 5.6.1 is required.
-      You can get a newer perl at http://www.cpan.org/src/index.html .
-    " >&2;}
-   { (exit 1); exit 1; }; }
-  fi
+#  if perl -e "exit( $perlver >= 5.006001 );"; then
+#    { { echo "$as_me:1909: error:
+#      Found perl version $perlver, but at least 5.6.1 is required.
+#      You can get a newer perl at http://www.cpan.org/src/index.html .
+#    " >&5
+#echo "$as_me: error:
+#      Found perl version $perlver, but at least 5.6.1 is required.
+#      You can get a newer perl at http://www.cpan.org/src/index.html .
+#    " >&2;}
+#   { (exit 1); exit 1; }; }
+#  fi
 
   perlport=`perl -e "print $^O;"`
   case "$perlport" in
