fixed most of the ./regrtest breakage from Makefile movement; fixed a configure script problem w.r.t config.status; made both Makefiles notice when they're out of date and regenerate automatically

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2519,6 +2519,7 @@ fi
 done
 
 ac_config_files="$ac_config_files Makefile test/Makefile"
+
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -2628,7 +2629,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:2631: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:2632: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -2795,7 +2796,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:2798: error: ambiguous option: $1
+    { { echo "$as_me:2799: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2818,12 +2819,12 @@ Try \`$0 --help' for more information." >&2;}
   'test/Makefile' ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:2821: error: unrecognized option: $1
+  -*) { { echo "$as_me:2822: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:2826: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:2827: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3048,7 +3049,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3051: creating $ac_file" >&5
+    { echo "$as_me:3052: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3066,7 +3067,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3069: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3070: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3079,7 +3080,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3082: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3083: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3105,6 +3106,11 @@ s,@top_srcdir@,$ac_top_srcdir,;t t
     rm -f $tmp/out
   fi
 
+  # Run the commands associated with the file.
+  case $ac_file in
+    Makefile ) chmod a-w Makefile test/Makefile ;;
+    test/Makefile ) chmod a-w Makefile test/Makefile ;;
+  esac
 done
 EOF
 
@@ -3133,4 +3139,3 @@ if test "$no_create" != yes; then
   $ac_cs_success || { (exit 1); exit 1; }
 fi
 
-chmod a-w Makefile test/Makefile
