ftpd-cured works!

diff --git a/lib/test-bad b/lib/test-bad
--- a/lib/test-bad
+++ b/lib/test-bad
@@ -16,6 +16,10 @@ cd "$CCUREDHOME/test/small2" || exit
 # read how many failure cases are in the file; expect line of form
 # "// NUMERRORS n"
 numcases=`grep NUMERRORS "$srcfile" | awk '{ print $3 }'`
+if [ -z "$numcases" ]; then
+  echo "didn't find a string of form NUMERRORS <n> in the file"
+  exit 2
+fi
 echo "there are $numcases failure cases in this file"
 
 # iterate through the cases; first case (0) is where no errors are present
